// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjucbqdyjjskudifxiqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqdWNicWR5ampza3VkaWZ4aXFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MzU5ODMsImV4cCI6MjA2NTAxMTk4M30.JCTgQxp65TDguYWjS0qGjI6hmf-VCwlnwWlI7S5RKZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);